### ISSUE TITLE
Change frontend deployment/hosting strategy

### ISSUE THREAD

**Issue by GabrielBuragev** [beamer-bridge/beamer#1388]
# Rationale
Currently, we are using DO Apps for the frontend deployment.
It takes ~15 minutes for a build to finish due to the submodule clutter in the repo (OP and Arb nodes).

We need to reconsider the hosting approach of our frontend.

# Implementation
- Use GH pages (setup a separate branch which will be used for hosting the static files)
- CI/GH jobs to build & deploy these static files (for example GitHub Actions should make it simple without much configuration: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site)
- Setup github pages inside repo settings
- Setup right permissions?

Downside of moving out from DO is that we lose the scaling capabilities of DO when the app has a lot of traffic.
At our current stage this is not worrysome. If we have the need to scale up our frontend app we might reconsider the approach.

# Acceptance Criteria
- [ ] Decide whether we need to use Circle CI or we can purely depend on GH
- [ ] GH workflow implemented and tested

**Comment by compojoom** [comment]
I don't understand why it has to be a DO droplet? The website is just html - we can build it in circleci and then push it to whatever service that can serve html (github, firebase, whatever)

**Comment by istankovic** [comment]
> 



> I don't understand why it has to be a DO droplet? The website is just html - we can build it in circleci and then push it to whatever service that can serve html (github, firebase, whatever)

:100:

**Comment by istankovic** [comment]
Another option that comes to mind and would be probably the least amount of work: check if there's a way to instruct DO not to clone submodules, since that is the part that takes the most time.

**Comment by manuelwedler** [comment]
I was reading into the documentation. With the current setup of a DO App, I don't see a way to change the git checkout process. I think we should go with what @compojoom said and just use a service for serving the static files

**Comment by GabrielBuragev** [comment]
Thanks for doing the research @manuelwedler! I also think that is the right approach.
Then, i will adjust the commit's description to reflect this decision.

**Comment by compojoom** [comment]
No, you can have a workflow for deploy that requires a manual start. We did it like this in trustlines.

**Comment by compojoom** [comment]
```
  release:
    jobs:
      - should_run:
          type: approval

      - checkout_code:
          <<: *only-develop-release-filter
          requires:
            - should_run

      - hold_ios_production:
          type: approval
          requires:
            - checkout_code

   
      - deploy_ios:
          name: deploy_ios_staging
          <<: *only-release-filter
          lane: deploy_staging
          requires:
            - hold_ios_staging

```

With this someone with the correct team permissions need to login in circleCI and click the button to start the lanes.

https://circleci.com/blog/adding-approval-jobs-to-your-ci-pipeline/
