### ISSUE TITLE
Introduce an agent config file

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#653]
In order to make the agent configuration easier and pave the way to multiple chain pairs support, we need to introduce a configuration file for the agent:

```bash
$ beamer-agent -c agent.conf
```

It should be possible to fully configure an agent just by using the configuration file i.e. no additional command line options should be necessary.

Additionally, we need to allow the user to configure multiple chain pairs:
```toml

log-level = "debug"                                                                     
deployment-dir = "deployments/rinkeby"                                                  
fill-wait-time = 120                                                                    
source-chain = "metis"
target-chain = "boba-rinkeby"
                                                                                        
[account]                                                                               
path = "/keys/UTC--2022-03-09T20-51-23.967Z--0x6626079bcf8c3241b082c73b74dfea46cefa4f02"
password = "foobar"                                                                     
                                                                                        
[metrics]                                                                               
prometheus-port = 9101                                                                  
                                                                                        
[chains.l1]                                                                             
rpc-url = "https://api-rinkeby.etherscan.io"                                            
                                                                                        
[chains.metis]                                                                          
rpc-url = "https://stardust.metis.io/?owner=588"                                        
                                                                                        
[chains.boba-rinkeby]                                                                   
rpc-url = "https://rinkeby.boba.network/"                                               
                                                                                        
[tokens]                                                                                
TST = [                                                                                 
    ["boba-rinkeby", "0x2644292EE5aed5c17BDcc6EDF1696ba802351cf6"],                     
    ["metis", "0xAcF5e964b76773166F69d6E53C1f7A9114a8E01D"]                             
]                                                                                       
                                                                                        
USDC = [                                                                                
    ["boba-rinkeby", "0x1a65113Fb92916EF0D3043D651b469b653763F16"],                     
    ["metis", "0x6bCE0F297a204E1374860E0259EC31047a87B50F"]                             
]                                                                                       
```
The above is in TOML format, to make it easier for humans.
Note that the above also includes the token match data, which obviates the need for a separate token match file.
It also has the added benefit of naming the tokens so that implementing a specific policy (e.g. forbidding a token on a specific chain) is made easier.

How we might go about implementing this issue:
- [ ] add a new command line option `-c`, `--config`
- [ ] have a default configuration in the agent that can be overridden by the config file and command line options, in that order
- [ ] replace the token match file with the `tokens` table from the config file
